In [ ]:
#https://www.youtube.com/watch?v=hSPmj7mK6ng
#https://github.com/Coding-with-Adam/Dash-by-Plotly/blob/master/Other/Dash_Introduction/intro.py

In [ ]:
import pandas as pd
import plotly.express as px  # (version 4.7.0)
import plotly.graph_objects as go

import dash  # (version 1.12.0) pip install dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(__name__)

# ---------- Import and clean data (importing csv into pandas)
# df = pd.read_csv('./intro_bees.csv')
df = pd.read_csv("https://raw.githubusercontent.com/Coding-with-Adam/Dash-by-Plotly/master/Other/Dash_Introduction/intro_bees.csv")

df = df.groupby(['State', 'ANSI', 'Affected by', 'Year', 'state_code'])[['Pct of Colonies Impacted']].mean()
df.reset_index(inplace=True)
print(df[:5])

# ------------------------------------------------------------------------------
# App layout
app.layout = html.Div([

    html.H1("Web Application Dashboards with Dash", style={'text-align': 'center'}),

    dcc.Dropdown(id="slct_year",
                 options=[
                     {"label": "2015", "value": 2015},
                     {"label": "2016", "value": 2016},
                     {"label": "2017", "value": 2017},
                     {"label": "2018", "value": 2018}],
                 multi=False,
                 value=2015,
                 style={'width': "40%"}
                 ),

    html.Div(id='output_container', children=[]),
    html.Br(),

    dcc.Graph(id='my_bee_map', figure={})

])


# ------------------------------------------------------------------------------
# Connect the Plotly graphs with Dash Components
@app.callback(
    [Output(component_id='output_container', component_property='children'),
     Output(component_id='my_bee_map', component_property='figure')],
    [Input(component_id='slct_year', component_property='value')]
)
def update_graph(option_slctd):
    print(option_slctd)
    print(type(option_slctd))

    container = "The year chosen by user was: {}".format(option_slctd)

    dff = df.copy()
    dff = dff[dff["Year"] == option_slctd]
    dff = dff[dff["Affected by"] == "Varroa_mites"]

    # Plotly Express
    fig = px.choropleth(
        data_frame=dff,
        locationmode='USA-states',
        locations='state_code',
        scope="usa",
        color='Pct of Colonies Impacted',
        hover_data=['State', 'Pct of Colonies Impacted'],
        color_continuous_scale=px.colors.sequential.YlOrRd,
        labels={'Pct of Colonies Impacted': '% of Bee Colonies'},
        template='plotly_dark'
    )

    # Plotly Graph Objects (GO)
    # fig = go.Figure(
    #     data=[go.Choropleth(
    #         locationmode='USA-states',
    #         locations=dff['state_code'],
    #         z=dff["Pct of Colonies Impacted"].astype(float),
    #         colorscale='Reds',
    #     )]
    # )
    #
    # fig.update_layout(
    #     title_text="Bees Affected by Mites in the USA",
    #     title_xanchor="center",
    #     title_font=dict(size=24),
    #     title_x=0.5,
    #     geo=dict(scope='usa'),
    # )

    return container, fig


# ------------------------------------------------------------------------------

# Unless you tell the development server that it's running in development mode,
# it will assume you're using it in production and warn you not to.
# i.e.
#    "Environment: production
#        WARNING: This is a development server. Do not use it in a production deployment.
#        Use a production WSGI server instead."

# The development server is not intended for use in production.
# It is not designed to be particularly efficient, stable, or secure.

# Instead, use a production WSGI server. 
# For example, to use Waitress, first install it in the virtual environment:

#    $ pip install waitress
# Next, tell Waitress about your application.
# You need to tell it to import and call the application factory to get an application object.
#    $ waitress-serve --call 'flaskr:create_app'
#    >>> Serving on http://0.0.0.0:8080
#    from waitress import serve
#    serve(app, host="0.0.0.0", port=8080)
if __name__ == '__main__':
    #app.run_server(debug=True)
    from waitress import serve
    serve(app, host="0.0.0.0", port=8080)
    
# https://youtu.be/hSPmj7mK6ng

In [2]:
df

        State  ANSI   Affected by  Year state_code  Pct of Colonies Impacted
0     Alabama     1       Disease  2015         AL                     0.050
1     Alabama     1       Disease  2016         AL                     1.200
2     Alabama     1       Disease  2017         AL                     2.250
3     Alabama     1       Disease  2018         AL                     1.300
4     Alabama     1       Disease  2019         AL                     1.800
...       ...   ...           ...   ...        ...                       ...
1345  Wyoming    56  Varroa_mites  2015         WY                    23.375
1346  Wyoming    56  Varroa_mites  2016         WY                    19.475
1347  Wyoming    56  Varroa_mites  2017         WY                    23.525
1348  Wyoming    56  Varroa_mites  2018         WY                    22.425
1349  Wyoming    56  Varroa_mites  2019         WY                     0.700

[1350 rows x 6 columns]